#!/usr/bin/python
import os
import sys
import time
import shutil

container_dir = "/var/lib/machines"
sync_dir = "/var/lib/containersync/machines"
tmp_dir = "/var/lib/containersync/tmp"

container = sys.argv[1]
if not container:
  print("You must specify a container")

if not os.path.isdir(os.path.join(container_dir, container)):
  print("Container does not exist (no directory %s)" % os.path.join(container_dir, container))

if not os.path.isdir(tmp_dir):
  os.makedirs(tmp_dir)

if not os.path.isdir(os.path.join(sync_dir, container)):
  print("Nothing to replace with")
  sys.exit()

current_time = os.path.getctime(os.path.join(container_dir, container))
new_time = os.path.getctime(os.path.join(sync_dir, container))

if new_time > current_time:
  shutil.move(os.path.join(container_dir, container), os.path.join(tmp_dir, container))
  shutil.move(os.path.join(sync_dir, container), container_dir)
  shutil.move(os.path.join(tmp_dir, container), os.path.join(sync_dir, container))
  print("Updated container %s" % container)
