#!/bin/bash

if [ "$#" -lt "1" ]; then
    echo "Usage: $1 <image-name>"
    exit 1
fi

basearch='$basearch'

cat > /etc/yum.repos.d/centos.repo <<EOF
[centos-base]
name=CentOS-7 - Base
#mirrorlist=http://mirrorlist.centos.org/?release=7&arch=basearch&repo=os
baseurl=http://mirror.centos.org/centos/7/os/$basearch/
enabled=0
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-5
priority=1

[centos-extras]
name=CentOS-7 - Extras
#mirrorlist=http://mirrorlist.centos.org/?release=7&arch=basearch&repo=extras
baseurl=http://mirror.centos.org/centos/7/extras/$basearch/
enabled=0
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-5
priority=1
EOF

/usr/bin/dnf --installroot=/srv/images/$1 --disablerepo '*' --enablerepo 'centos-base' --enablerepo 'centos-extras' -y groupinstall core
/usr/bin/dnf --installroot=/srv/images/$1 --disablerepo '*' --enablerepo 'centos-base' --enablerepo 'centos-extras' -y install epel-release iproute

sed -i 's|^root:.*$|root:$6$oisdfoiaj$rffY1PXLJ5DLMOV/nmA8elQRRNbq8hgK7K/WZsXc3SOvmFZd6qRYXRH9IttsQ7x3yXbShSbJcn9h0j7/T7uQC1:14871::::::|' /srv/images/$1/etc/shadow

test -e /srv/images/$1/etc/resolv.conf || cp /etc/resolv.conf /srv/images/$1/etc/resolv.conf

chroot /srv/images/$1 /usr/bin/yum -y install salt-minion
