# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

pref("app.update.lastUpdateTime.addon-background-update-timer", 1455068383);
pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1455068503);
pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1455068743);
pref("app.update.lastUpdateTime.experiments-update-timer", 1452447972);
pref("app.update.lastUpdateTime.search-engine-update-timer", 1443399772);
pref("app.update.lastUpdateTime.xpi-signature-verification", 1455068623);
pref("browser.bookmarks.restore_default_bookmarks", false);
pref("browser.cache.disk.capacity", 358400);
pref("browser.cache.disk.filesystem_reported", 1);
pref("browser.cache.disk.smart_size.first_run", false);
pref("browser.cache.frecency_experiment", 4);
pref("browser.download.importedFromSqlite", true);
pref("browser.formfill.enable", false);
pref("browser.formfill.saveHttpsForms", false);
pref("browser.migration.version", 31);
pref("browser.newtabpage.enhanced", true);
pref("browser.newtabpage.introShown", true);
pref("browser.newtabpage.storageVersion", 1);
pref("browser.pagethumbnails.storage_version", 3);
pref("browser.places.smartBookmarksVersion", 7);
pref("browser.reader.detectedFirstArticle", true);
pref("browser.rights.3.shown", true);
pref("browser.search.countryCode", "US");
pref("browser.search.region", "US");
pref("browser.sessionstore.upgradeBackup.latestBuildID", "20151229124055");
pref("browser.slowStartup.averageTime", 0);
pref("browser.slowStartup.samples", 0);
pref("browser.startup.homepage_override.buildID", "20151229124055");
pref("browser.startup.homepage_override.mstone", "43.0.3");
pref("browser.toolbarbuttons.introduced.pocket-button", true);
pref("datareporting.healthreport.nextDataSubmissionTime", "1443485931468");
pref("datareporting.healthreport.service.firstRun", true);
pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1443399592752");
pref("datareporting.policy.firstRunTime", "1443399531468");
pref("datareporting.sessions.current.activeTicks", 9);
pref("datareporting.sessions.current.clean", true);
pref("datareporting.sessions.current.firstPaint", 6236);
pref("datareporting.sessions.current.main", 2711);
pref("datareporting.sessions.current.sessionRestored", 6292);
pref("datareporting.sessions.current.startTime", "1455747111563");
pref("datareporting.sessions.current.totalTime", 48);
pref("datareporting.sessions.currentIndex", 9);
pref("datareporting.sessions.previous.0", "{\"s\":1443399530927,\"a\":15,\"t\":329,\"c\":true,\"m\":152,\"fp\":1939,\"sr\":1823}");
pref("datareporting.sessions.previous.1", "{\"s\":1452447850385,\"a\":15,\"t\":143,\"c\":true,\"m\":110,\"fp\":5873,\"sr\":5827}");
pref("datareporting.sessions.previous.2", "{\"s\":1453444986438,\"a\":5,\"t\":25,\"c\":true,\"m\":191,\"fp\":3911,\"sr\":3816}");
pref("datareporting.sessions.previous.3", "{\"s\":1453768686330,\"a\":2,\"t\":25,\"c\":true,\"m\":191,\"fp\":9375,\"sr\":9277}");
pref("datareporting.sessions.previous.4", "{\"s\":1454448610114,\"a\":2,\"t\":17,\"c\":true,\"m\":181,\"fp\":2487,\"sr\":-1}");
pref("datareporting.sessions.previous.5", "{\"s\":1454449715261,\"a\":1,\"t\":6,\"c\":true,\"m\":111,\"fp\":1283,\"sr\":1738}");
pref("datareporting.sessions.previous.6", "{\"s\":1454656156653,\"a\":2,\"t\":11,\"c\":true,\"m\":70,\"fp\":1185,\"sr\":2031}");
pref("datareporting.sessions.previous.7", "{\"s\":1455068262070,\"a\":13,\"t\":2155,\"c\":true,\"m\":211,\"fp\":2379,\"sr\":2648}");
pref("datareporting.sessions.previous.8", "{\"s\":1455082561589,\"a\":1,\"t\":6,\"c\":true,\"m\":1851,\"fp\":-1,\"sr\":-1}");
pref("dom.apps.reset-permissions", true);
pref("dom.mozApps.used", true);
pref("experiments.activeExperiment", false);
pref("extensions.blocklist.pingCountVersion", -1);
pref("extensions.bootstrappedAddons", "{}");
pref("extensions.databaseSchema", 17);
pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:43.0.3");
pref("extensions.getAddons.cache.lastUpdate", 1455068383);
pref("extensions.getAddons.databaseSchema", 5);
pref("extensions.lastAppVersion", "43.0.3");
pref("extensions.lastPlatformVersion", "43.0.3");
pref("extensions.pendingOperations", false);
pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"43.0.3\",\"st\":1453433373000,\"mt\":1451394474000}}}");
pref("gecko.buildID", "20151229124055");
pref("gecko.mstone", "43.0.3");
pref("idle.lastDailyNotification", 1443399773);
pref("media.gmp-manager.buildID", "20151229124055");
pref("media.gmp-manager.lastCheck", 1455068325);
pref("network.cookie.prefsMigrated", true);
pref("network.predictor.cleaned-up", true);
pref("pdfjs.migrationVersion", 2);
pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
pref("pdfjs.previousHandler.preferredAction", 4);
pref("places.database.lastMaintenance", 1443399773);
pref("places.history.expiration.transient_current_max_pages", 54375);
pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
pref("plugin.importedState", true);
pref("privacy.sanitize.migrateFx3Prefs", true);
pref("services.sync.prefs.sync.browser.formfill.enable", false);
lockPref("services.sync.prefs.sync.browser.formfill.enable");
pref("signon.autofillForms", false);
lockPref("signon.autofillForms");
pref("signon.importedFromSqlite", true);
pref("storage.vacuum.last.index", 0);
pref("storage.vacuum.last.places.sqlite", 1443399773);
pref("toolkit.startup.last_success", 1455747114);
pref("toolkit.telemetry.cachedClientID", "2a9163d5-ab20-488c-b76c-042a8c09cd76");
pref("toolkit.telemetry.previousBuildID", "20151229124055");
pref("toolkit.telemetry.reportingpolicy.firstRun", false);
pref("browser.startup.homepage", "data:text/plain,browser.startup.homepage=http://onsite.uber.magfest.org");
lockPref("browser.startup.homepage");
